# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oneflow/customized/utils/projector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='oneflow/customized/utils/projector.proto',
  package='oneflow',
  syntax='proto2',
  serialized_pb=_b('\n(oneflow/customized/utils/projector.proto\x12\x07oneflow\"y\n\x08MetaData\x12-\n\x04type\x18\x01 \x02(\x0e\x32\x1f.oneflow.MetaData.ProjectorType\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"-\n\rProjectorType\x12\r\n\tEMBEDDING\x10\x00\x12\r\n\tEXCEPTION\x10\x01\"\xb4\x01\n\x06Tensor\x12\r\n\x05\x64type\x18\x01 \x02(\t\x12*\n\x05shape\x18\x02 \x02(\x0b\x32\x1b.oneflow.Tensor.TensorShape\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\x1a^\n\x0bTensorShape\x12,\n\x03\x64im\x18\x01 \x03(\x0b\x32\x1f.oneflow.Tensor.TensorShape.Dim\x1a!\n\x03\x44im\x12\x0c\n\x04size\x18\x01 \x02(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x8a\x01\n\x06Sample\x12\x0c\n\x04name\x18\x01 \x02(\t\x12(\n\x04type\x18\x02 \x02(\x0e\x32\x1a.oneflow.Sample.SampleType\x12\x1a\n\x01X\x18\x03 \x02(\x0b\x32\x0f.oneflow.Tensor\",\n\nSampleType\x12\t\n\x05IMAGE\x10\x00\x12\t\n\x05\x41UDIO\x10\x01\x12\x08\n\x04TEXT\x10\x02\"y\n\tProjector\x12\x0b\n\x03tag\x18\x01 \x02(\t\x12\x0c\n\x04step\x18\x02 \x01(\x03\x12\x11\n\tWALL_TIME\x18\x03 \x02(\x01\x12\x1e\n\x05value\x18\x04 \x02(\x0b\x32\x0f.oneflow.Tensor\x12\x1e\n\x05label\x18\x05 \x01(\x0b\x32\x0f.oneflow.Tensor\"\x7f\n\x10SummaryProjector\x12#\n\x08metadata\x18\x06 \x02(\x0b\x32\x11.oneflow.MetaData\x12\x1f\n\x06sample\x18\x02 \x01(\x0b\x32\x0f.oneflow.Sample\x12%\n\tprojector\x18\x01 \x03(\x0b\x32\x12.oneflow.Projector')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_METADATA_PROJECTORTYPE = _descriptor.EnumDescriptor(
  name='ProjectorType',
  full_name='oneflow.MetaData.ProjectorType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EMBEDDING', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXCEPTION', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=129,
  serialized_end=174,
)
_sym_db.RegisterEnumDescriptor(_METADATA_PROJECTORTYPE)

_SAMPLE_SAMPLETYPE = _descriptor.EnumDescriptor(
  name='SampleType',
  full_name='oneflow.Sample.SampleType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IMAGE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUDIO', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEXT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=454,
  serialized_end=498,
)
_sym_db.RegisterEnumDescriptor(_SAMPLE_SAMPLETYPE)


_METADATA = _descriptor.Descriptor(
  name='MetaData',
  full_name='oneflow.MetaData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='oneflow.MetaData.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='oneflow.MetaData.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _METADATA_PROJECTORTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=174,
)


_TENSOR_TENSORSHAPE_DIM = _descriptor.Descriptor(
  name='Dim',
  full_name='oneflow.Tensor.TensorShape.Dim',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='oneflow.Tensor.TensorShape.Dim.size', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='oneflow.Tensor.TensorShape.Dim.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=357,
)

_TENSOR_TENSORSHAPE = _descriptor.Descriptor(
  name='TensorShape',
  full_name='oneflow.Tensor.TensorShape',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dim', full_name='oneflow.Tensor.TensorShape.dim', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TENSOR_TENSORSHAPE_DIM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=357,
)

_TENSOR = _descriptor.Descriptor(
  name='Tensor',
  full_name='oneflow.Tensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dtype', full_name='oneflow.Tensor.dtype', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shape', full_name='oneflow.Tensor.shape', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='oneflow.Tensor.content', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TENSOR_TENSORSHAPE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=357,
)


_SAMPLE = _descriptor.Descriptor(
  name='Sample',
  full_name='oneflow.Sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='oneflow.Sample.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='oneflow.Sample.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='X', full_name='oneflow.Sample.X', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SAMPLE_SAMPLETYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=498,
)


_PROJECTOR = _descriptor.Descriptor(
  name='Projector',
  full_name='oneflow.Projector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag', full_name='oneflow.Projector.tag', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='step', full_name='oneflow.Projector.step', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='WALL_TIME', full_name='oneflow.Projector.WALL_TIME', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='oneflow.Projector.value', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label', full_name='oneflow.Projector.label', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=500,
  serialized_end=621,
)


_SUMMARYPROJECTOR = _descriptor.Descriptor(
  name='SummaryProjector',
  full_name='oneflow.SummaryProjector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata', full_name='oneflow.SummaryProjector.metadata', index=0,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample', full_name='oneflow.SummaryProjector.sample', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='projector', full_name='oneflow.SummaryProjector.projector', index=2,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=623,
  serialized_end=750,
)

_METADATA.fields_by_name['type'].enum_type = _METADATA_PROJECTORTYPE
_METADATA_PROJECTORTYPE.containing_type = _METADATA
_TENSOR_TENSORSHAPE_DIM.containing_type = _TENSOR_TENSORSHAPE
_TENSOR_TENSORSHAPE.fields_by_name['dim'].message_type = _TENSOR_TENSORSHAPE_DIM
_TENSOR_TENSORSHAPE.containing_type = _TENSOR
_TENSOR.fields_by_name['shape'].message_type = _TENSOR_TENSORSHAPE
_SAMPLE.fields_by_name['type'].enum_type = _SAMPLE_SAMPLETYPE
_SAMPLE.fields_by_name['X'].message_type = _TENSOR
_SAMPLE_SAMPLETYPE.containing_type = _SAMPLE
_PROJECTOR.fields_by_name['value'].message_type = _TENSOR
_PROJECTOR.fields_by_name['label'].message_type = _TENSOR
_SUMMARYPROJECTOR.fields_by_name['metadata'].message_type = _METADATA
_SUMMARYPROJECTOR.fields_by_name['sample'].message_type = _SAMPLE
_SUMMARYPROJECTOR.fields_by_name['projector'].message_type = _PROJECTOR
DESCRIPTOR.message_types_by_name['MetaData'] = _METADATA
DESCRIPTOR.message_types_by_name['Tensor'] = _TENSOR
DESCRIPTOR.message_types_by_name['Sample'] = _SAMPLE
DESCRIPTOR.message_types_by_name['Projector'] = _PROJECTOR
DESCRIPTOR.message_types_by_name['SummaryProjector'] = _SUMMARYPROJECTOR

MetaData = _reflection.GeneratedProtocolMessageType('MetaData', (_message.Message,), dict(
  DESCRIPTOR = _METADATA,
  __module__ = 'oneflow.customized.utils.projector_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.MetaData)
  ))
_sym_db.RegisterMessage(MetaData)

Tensor = _reflection.GeneratedProtocolMessageType('Tensor', (_message.Message,), dict(

  TensorShape = _reflection.GeneratedProtocolMessageType('TensorShape', (_message.Message,), dict(

    Dim = _reflection.GeneratedProtocolMessageType('Dim', (_message.Message,), dict(
      DESCRIPTOR = _TENSOR_TENSORSHAPE_DIM,
      __module__ = 'oneflow.customized.utils.projector_pb2'
      # @@protoc_insertion_point(class_scope:oneflow.Tensor.TensorShape.Dim)
      ))
    ,
    DESCRIPTOR = _TENSOR_TENSORSHAPE,
    __module__ = 'oneflow.customized.utils.projector_pb2'
    # @@protoc_insertion_point(class_scope:oneflow.Tensor.TensorShape)
    ))
  ,
  DESCRIPTOR = _TENSOR,
  __module__ = 'oneflow.customized.utils.projector_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.Tensor)
  ))
_sym_db.RegisterMessage(Tensor)
_sym_db.RegisterMessage(Tensor.TensorShape)
_sym_db.RegisterMessage(Tensor.TensorShape.Dim)

Sample = _reflection.GeneratedProtocolMessageType('Sample', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLE,
  __module__ = 'oneflow.customized.utils.projector_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.Sample)
  ))
_sym_db.RegisterMessage(Sample)

Projector = _reflection.GeneratedProtocolMessageType('Projector', (_message.Message,), dict(
  DESCRIPTOR = _PROJECTOR,
  __module__ = 'oneflow.customized.utils.projector_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.Projector)
  ))
_sym_db.RegisterMessage(Projector)

SummaryProjector = _reflection.GeneratedProtocolMessageType('SummaryProjector', (_message.Message,), dict(
  DESCRIPTOR = _SUMMARYPROJECTOR,
  __module__ = 'oneflow.customized.utils.projector_pb2'
  # @@protoc_insertion_point(class_scope:oneflow.SummaryProjector)
  ))
_sym_db.RegisterMessage(SummaryProjector)


# @@protoc_insertion_point(module_scope)
